"""empty message

Revision ID: 08f038fa9bd8
Revises: 8faf4c93a353
Create Date: 2023-09-21 10:46:49.301309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f038fa9bd8'
down_revision = '8faf4c93a353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation_deep_tbl', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relation_deep_tbl', 'user_id')
    # ### end Alembic commands ###
