"""empty message

Revision ID: 8faf4c93a353
Revises: 
Create Date: 2023-09-21 10:45:56.316220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8faf4c93a353'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_tbl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增id'),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_tbl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增id'),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('record', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation_deep_tbl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增id'),
    sa.Column('deep_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tbl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增id'),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tbl')
    op.drop_table('relation_deep_tbl')
    op.drop_table('record_tbl')
    op.drop_table('group_tbl')
    # ### end Alembic commands ###
